server:
  port: 12211
  servlet:
    context-path: /market
eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
spring:
  application:
    name: hystrix-client
